package
{
	import com.thaumaturgistgames.flakit.Library;
	import flash.utils.ByteArray;
	
	/**
	* Generated with LibraryBuilder for FLAKit
	* http://www.thaumaturgistgames.com/FLAKit
	*/
	public class EmbeddedAssets
	{
		[Embed(source = "../lib/ogmo/ambiance.png")] private const FLAKIT_ASSET$26896941:Class;
		[Embed(source = "../lib/ogmo/background.png")] private const FLAKIT_ASSET$_1157757234:Class;
		[Embed(source = "../lib/ogmo/camera.png")] private const FLAKIT_ASSET$_862204225:Class;
		[Embed(source = "../lib/ogmo/climate.png")] private const FLAKIT_ASSET$910413312:Class;
		[Embed(source = "../lib/ogmo/Decal.png")] private const FLAKIT_ASSET$338515033:Class;
		[Embed(source = "../lib/ogmo/emitter.png")] private const FLAKIT_ASSET$_438935123:Class;
		[Embed(source = "../lib/ogmo/footsteps.png")] private const FLAKIT_ASSET$_1233139147:Class;
		[Embed(source = "../lib/ogmo/humphrey.png")] private const FLAKIT_ASSET$_1285077015:Class;
		[Embed(source = "../lib/ogmo/invitem.png")] private const FLAKIT_ASSET$_612164355:Class;
		[Embed(source = "../lib/ogmo/overworld.png")] private const FLAKIT_ASSET$_1221571681:Class;
		[Embed(source = "../lib/ogmo/script.png")] private const FLAKIT_ASSET$1622622818:Class;
		[Embed(source = "../lib/ogmo/smallhumphrey.png")] private const FLAKIT_ASSET$1909618802:Class;
		[Embed(source = "../lib/ogmo/worldreaction.png")] private const FLAKIT_ASSET$_386300015:Class;
		[Embed(source = "../lib/ogmo/worldSound.png")] private const FLAKIT_ASSET$1161070485:Class;
		[Embed(source = "../lib/art/ball.png")] private const FLAKIT_ASSET$_2019615363:Class;
		[Embed(source = "../lib/art/balloon.png")] private const FLAKIT_ASSET$_1807772156:Class;
		[Embed(source = "../lib/art/HTA.png")] private const FLAKIT_ASSET$_836379087:Class;
		[Embed(source = "../lib/art/humphrey_poses.png")] private const FLAKIT_ASSET$710661133:Class;
		[Embed(source = "../lib/art/journal.png")] private const FLAKIT_ASSET$_1303404286:Class;
		[Embed(source = "../lib/art/small_humphrey.png")] private const FLAKIT_ASSET$_1880102885:Class;
		[Embed(source = "../lib/art/spinky_poses.png")] private const FLAKIT_ASSET$1700783116:Class;
		[Embed(source = "../lib/art/thought_backpack.png")] private const FLAKIT_ASSET$_1567996301:Class;
		[Embed(source = "../lib/art/thought_heat.png")] private const FLAKIT_ASSET$817083425:Class;
		[Embed(source = "../lib/art/snow/snowdrift.png")] private const FLAKIT_ASSET$360635201:Class;
		[Embed(source = "../lib/art/snow/snowflake.png")] private const FLAKIT_ASSET$1532032240:Class;
		[Embed(source = "../lib/art/snow/snow_exterior.png")] private const FLAKIT_ASSET$_1731975245:Class;
		[Embed(source = "../lib/art/snow/thought_big_heart.png")] private const FLAKIT_ASSET$1026734727:Class;
		[Embed(source = "../lib/art/snow/thought_small_heart.png")] private const FLAKIT_ASSET$520857850:Class;
		[Embed(source = "../lib/art/Scene 1/backpack.png")] private const FLAKIT_ASSET$1013030486:Class;
		[Embed(source = "../lib/art/Scene 1/chair.png")] private const FLAKIT_ASSET$1677560858:Class;
		[Embed(source = "../lib/art/Scene 1/humphrey_sitting.png")] private const FLAKIT_ASSET$_952051180:Class;
		[Embed(source = "../lib/art/Scene 1/scene1.png")] private const FLAKIT_ASSET$408775711:Class;
		[Embed(source = "../lib/art/Scene 1/thought_play.png")] private const FLAKIT_ASSET$_303027495:Class;
		[Embed(source = "../lib/art/Scene 1/thought_where_spinky.png")] private const FLAKIT_ASSET$_1730391772:Class;
		[Embed(source = "../lib/art/Scene 1/thought_work.png")] private const FLAKIT_ASSET$_116638233:Class;
		[Embed(source = "../lib/art/Scene 1/thought_worry.png")] private const FLAKIT_ASSET$1325928848:Class;
		[Embed(source = "../lib/art/pickups/backpack.png")] private const FLAKIT_ASSET$_3860730:Class;
		[Embed(source = "../lib/art/pickups/journal.png")] private const FLAKIT_ASSET$_2032973506:Class;
		[Embed(source = "../lib/art/particles/flame_01.png")] private const FLAKIT_ASSET$_1946428317:Class;
		[Embed(source = "../lib/art/particles/flame_02.png")] private const FLAKIT_ASSET$_1956717469:Class;
		[Embed(source = "../lib/art/particles/flame_03.png")] private const FLAKIT_ASSET$_1958880157:Class;
		[Embed(source = "../lib/art/particles/smoke.png")] private const FLAKIT_ASSET$_489507794:Class;
		[Embed(source = "../lib/art/particles/snowflake.png")] private const FLAKIT_ASSET$_430274975:Class;
		[Embed(source = "../lib/art/forest/bluejay.png")] private const FLAKIT_ASSET$_769341006:Class;
		[Embed(source = "../lib/art/forest/forest.png")] private const FLAKIT_ASSET$666618955:Class;
		[Embed(source = "../lib/art/forest/owl.png")] private const FLAKIT_ASSET$34050437:Class;
		[Embed(source = "../lib/art/forest/robin.png")] private const FLAKIT_ASSET$_428565781:Class;
		[Embed(source = "../lib/art/forest/THOUGHT_ICE.PNG")] private const FLAKIT_ASSET$1825604631:Class;
		[Embed(source = "../lib/art/forest/THOUGHT_SPINKY_CRASH.PNG")] private const FLAKIT_ASSET$282746940:Class;
		[Embed(source = "../lib/art/forest/THOUGHT_SPINKY_TRY_FLY.PNG")] private const FLAKIT_ASSET$1434836898:Class;
		[Embed(source = "../lib/art/desert/desert.png")] private const FLAKIT_ASSET$_866044821:Class;
		[Embed(source = "../lib/art/desert/HAND_JOURNAL.PNG")] private const FLAKIT_ASSET$_1469665351:Class;
		[Embed(source = "../lib/art/desert/thought_alert_melt.png")] private const FLAKIT_ASSET$_284917921:Class;
		[Embed(source = "../lib/art/desert/thought_city.png")] private const FLAKIT_ASSET$223420480:Class;
		[Embed(source = "../lib/art/decals/chair.png")] private const FLAKIT_ASSET$2847401:Class;
		[Embed(source = "../lib/art/decals/ice_block.png")] private const FLAKIT_ASSET$353445110:Class;
		[Embed(source = "../lib/art/city/balloon_guy.png")] private const FLAKIT_ASSET$_1765834530:Class;
		[Embed(source = "../lib/art/city/city.png")] private const FLAKIT_ASSET$_2021297012:Class;
		[Embed(source = "../lib/art/city/cop.png")] private const FLAKIT_ASSET$_1347494723:Class;
		[Embed(source = "../lib/art/city/no_exit.png")] private const FLAKIT_ASSET$2004647526:Class;
		[Embed(source = "../lib/art/city/no_penguins.png")] private const FLAKIT_ASSET$1747383944:Class;
		[Embed(source = "../lib/art/city/thought_forest.png")] private const FLAKIT_ASSET$_1489954762:Class;
		[Embed(source = "../lib/art/city/thought_no_exit.png")] private const FLAKIT_ASSET$745487832:Class;
		[Embed(source = "../lib/art/city/thought_no_penguins.png")] private const FLAKIT_ASSET$537815089:Class;
		[Embed(source = "../lib/art/city/thought_penguin_balloon.png")] private const FLAKIT_ASSET$_927177735:Class;
		[Embed(source = "../lib/art/city/thought_penguin_balloon_guy.png")] private const FLAKIT_ASSET$_1382220419:Class;
		[Embed(source = "../lib/art/characters/humphrey.png")] private const FLAKIT_ASSET$1976508815:Class;
		[Embed(source = "../lib/art/backgrounds/overworld.png")] private const FLAKIT_ASSET$_1423972293:Class;
		[Embed(source = "../lib/art/backgrounds/snow-basketball.png")] private const FLAKIT_ASSET$_1317921299:Class;
		[Embed(source = "../lib/art/backgrounds/snow-hub.png")] private const FLAKIT_ASSET$_144923090:Class;
		[Embed(source = "../lib/art/backgrounds/snow-pond.png")] private const FLAKIT_ASSET$1743609987:Class;
		[Embed(source = "../lib/art/backgrounds/start.png")] private const FLAKIT_ASSET$_782423215:Class;
		[Embed(source = "../lib/sounds/windHowl.mp3")] private const FLAKIT_ASSET$_531661301:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-2.mp3")] private const FLAKIT_ASSET$_1434075057:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-3.mp3")] private const FLAKIT_ASSET$_1797078961:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-4.mp3")] private const FLAKIT_ASSET$1292877903:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-5.mp3")] private const FLAKIT_ASSET$_1835745201:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step.mp3")] private const FLAKIT_ASSET$_11183610:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step-2.mp3")] private const FLAKIT_ASSET$_487780191:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step-3.mp3")] private const FLAKIT_ASSET$_353890143:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step.mp3")] private const FLAKIT_ASSET$_225120446:Class;
		[Embed(source = "../lib/Library.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_1371418527:Class;
		[Embed(source = "../lib/worlds/start/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_475205487:Class;
		[Embed(source = "../lib/worlds/snow-pond/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1886460785:Class;
		[Embed(source = "../lib/worlds/snow-hub/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$404816983:Class;
		[Embed(source = "../lib/worlds/snow-basketball/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$2134780036:Class;
		[Embed(source = "../lib/worlds/overworld/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$573320175:Class;
		[Embed(source = "../lib/scripts/rotateWorld.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1821305064:Class;
		
		public function EmbeddedAssets()
		{
			Library.addImage(new String("ogmo/ambiance.png").split("/").join("."), new FLAKIT_ASSET$26896941);
			Library.addImage(new String("ogmo/background.png").split("/").join("."), new FLAKIT_ASSET$_1157757234);
			Library.addImage(new String("ogmo/camera.png").split("/").join("."), new FLAKIT_ASSET$_862204225);
			Library.addImage(new String("ogmo/climate.png").split("/").join("."), new FLAKIT_ASSET$910413312);
			Library.addImage(new String("ogmo/Decal.png").split("/").join("."), new FLAKIT_ASSET$338515033);
			Library.addImage(new String("ogmo/emitter.png").split("/").join("."), new FLAKIT_ASSET$_438935123);
			Library.addImage(new String("ogmo/footsteps.png").split("/").join("."), new FLAKIT_ASSET$_1233139147);
			Library.addImage(new String("ogmo/humphrey.png").split("/").join("."), new FLAKIT_ASSET$_1285077015);
			Library.addImage(new String("ogmo/invitem.png").split("/").join("."), new FLAKIT_ASSET$_612164355);
			Library.addImage(new String("ogmo/overworld.png").split("/").join("."), new FLAKIT_ASSET$_1221571681);
			Library.addImage(new String("ogmo/script.png").split("/").join("."), new FLAKIT_ASSET$1622622818);
			Library.addImage(new String("ogmo/smallhumphrey.png").split("/").join("."), new FLAKIT_ASSET$1909618802);
			Library.addImage(new String("ogmo/worldreaction.png").split("/").join("."), new FLAKIT_ASSET$_386300015);
			Library.addImage(new String("ogmo/worldSound.png").split("/").join("."), new FLAKIT_ASSET$1161070485);
			Library.addImage(new String("art/ball.png").split("/").join("."), new FLAKIT_ASSET$_2019615363);
			Library.addImage(new String("art/balloon.png").split("/").join("."), new FLAKIT_ASSET$_1807772156);
			Library.addImage(new String("art/HTA.png").split("/").join("."), new FLAKIT_ASSET$_836379087);
			Library.addImage(new String("art/humphrey_poses.png").split("/").join("."), new FLAKIT_ASSET$710661133);
			Library.addImage(new String("art/journal.png").split("/").join("."), new FLAKIT_ASSET$_1303404286);
			Library.addImage(new String("art/small_humphrey.png").split("/").join("."), new FLAKIT_ASSET$_1880102885);
			Library.addImage(new String("art/spinky_poses.png").split("/").join("."), new FLAKIT_ASSET$1700783116);
			Library.addImage(new String("art/thought_backpack.png").split("/").join("."), new FLAKIT_ASSET$_1567996301);
			Library.addImage(new String("art/thought_heat.png").split("/").join("."), new FLAKIT_ASSET$817083425);
			Library.addImage(new String("art/snow/snowdrift.png").split("/").join("."), new FLAKIT_ASSET$360635201);
			Library.addImage(new String("art/snow/snowflake.png").split("/").join("."), new FLAKIT_ASSET$1532032240);
			Library.addImage(new String("art/snow/snow_exterior.png").split("/").join("."), new FLAKIT_ASSET$_1731975245);
			Library.addImage(new String("art/snow/thought_big_heart.png").split("/").join("."), new FLAKIT_ASSET$1026734727);
			Library.addImage(new String("art/snow/thought_small_heart.png").split("/").join("."), new FLAKIT_ASSET$520857850);
			Library.addImage(new String("art/Scene 1/backpack.png").split("/").join("."), new FLAKIT_ASSET$1013030486);
			Library.addImage(new String("art/Scene 1/chair.png").split("/").join("."), new FLAKIT_ASSET$1677560858);
			Library.addImage(new String("art/Scene 1/humphrey_sitting.png").split("/").join("."), new FLAKIT_ASSET$_952051180);
			Library.addImage(new String("art/Scene 1/scene1.png").split("/").join("."), new FLAKIT_ASSET$408775711);
			Library.addImage(new String("art/Scene 1/thought_play.png").split("/").join("."), new FLAKIT_ASSET$_303027495);
			Library.addImage(new String("art/Scene 1/thought_where_spinky.png").split("/").join("."), new FLAKIT_ASSET$_1730391772);
			Library.addImage(new String("art/Scene 1/thought_work.png").split("/").join("."), new FLAKIT_ASSET$_116638233);
			Library.addImage(new String("art/Scene 1/thought_worry.png").split("/").join("."), new FLAKIT_ASSET$1325928848);
			Library.addImage(new String("art/pickups/backpack.png").split("/").join("."), new FLAKIT_ASSET$_3860730);
			Library.addImage(new String("art/pickups/journal.png").split("/").join("."), new FLAKIT_ASSET$_2032973506);
			Library.addImage(new String("art/particles/flame_01.png").split("/").join("."), new FLAKIT_ASSET$_1946428317);
			Library.addImage(new String("art/particles/flame_02.png").split("/").join("."), new FLAKIT_ASSET$_1956717469);
			Library.addImage(new String("art/particles/flame_03.png").split("/").join("."), new FLAKIT_ASSET$_1958880157);
			Library.addImage(new String("art/particles/smoke.png").split("/").join("."), new FLAKIT_ASSET$_489507794);
			Library.addImage(new String("art/particles/snowflake.png").split("/").join("."), new FLAKIT_ASSET$_430274975);
			Library.addImage(new String("art/forest/bluejay.png").split("/").join("."), new FLAKIT_ASSET$_769341006);
			Library.addImage(new String("art/forest/forest.png").split("/").join("."), new FLAKIT_ASSET$666618955);
			Library.addImage(new String("art/forest/owl.png").split("/").join("."), new FLAKIT_ASSET$34050437);
			Library.addImage(new String("art/forest/robin.png").split("/").join("."), new FLAKIT_ASSET$_428565781);
			Library.addImage(new String("art/forest/THOUGHT_ICE.PNG").split("/").join("."), new FLAKIT_ASSET$1825604631);
			Library.addImage(new String("art/forest/THOUGHT_SPINKY_CRASH.PNG").split("/").join("."), new FLAKIT_ASSET$282746940);
			Library.addImage(new String("art/forest/THOUGHT_SPINKY_TRY_FLY.PNG").split("/").join("."), new FLAKIT_ASSET$1434836898);
			Library.addImage(new String("art/desert/desert.png").split("/").join("."), new FLAKIT_ASSET$_866044821);
			Library.addImage(new String("art/desert/HAND_JOURNAL.PNG").split("/").join("."), new FLAKIT_ASSET$_1469665351);
			Library.addImage(new String("art/desert/thought_alert_melt.png").split("/").join("."), new FLAKIT_ASSET$_284917921);
			Library.addImage(new String("art/desert/thought_city.png").split("/").join("."), new FLAKIT_ASSET$223420480);
			Library.addImage(new String("art/decals/chair.png").split("/").join("."), new FLAKIT_ASSET$2847401);
			Library.addImage(new String("art/decals/ice_block.png").split("/").join("."), new FLAKIT_ASSET$353445110);
			Library.addImage(new String("art/city/balloon_guy.png").split("/").join("."), new FLAKIT_ASSET$_1765834530);
			Library.addImage(new String("art/city/city.png").split("/").join("."), new FLAKIT_ASSET$_2021297012);
			Library.addImage(new String("art/city/cop.png").split("/").join("."), new FLAKIT_ASSET$_1347494723);
			Library.addImage(new String("art/city/no_exit.png").split("/").join("."), new FLAKIT_ASSET$2004647526);
			Library.addImage(new String("art/city/no_penguins.png").split("/").join("."), new FLAKIT_ASSET$1747383944);
			Library.addImage(new String("art/city/thought_forest.png").split("/").join("."), new FLAKIT_ASSET$_1489954762);
			Library.addImage(new String("art/city/thought_no_exit.png").split("/").join("."), new FLAKIT_ASSET$745487832);
			Library.addImage(new String("art/city/thought_no_penguins.png").split("/").join("."), new FLAKIT_ASSET$537815089);
			Library.addImage(new String("art/city/thought_penguin_balloon.png").split("/").join("."), new FLAKIT_ASSET$_927177735);
			Library.addImage(new String("art/city/thought_penguin_balloon_guy.png").split("/").join("."), new FLAKIT_ASSET$_1382220419);
			Library.addImage(new String("art/characters/humphrey.png").split("/").join("."), new FLAKIT_ASSET$1976508815);
			Library.addImage(new String("art/backgrounds/overworld.png").split("/").join("."), new FLAKIT_ASSET$_1423972293);
			Library.addImage(new String("art/backgrounds/snow-basketball.png").split("/").join("."), new FLAKIT_ASSET$_1317921299);
			Library.addImage(new String("art/backgrounds/snow-hub.png").split("/").join("."), new FLAKIT_ASSET$_144923090);
			Library.addImage(new String("art/backgrounds/snow-pond.png").split("/").join("."), new FLAKIT_ASSET$1743609987);
			Library.addImage(new String("art/backgrounds/start.png").split("/").join("."), new FLAKIT_ASSET$_782423215);
			Library.addSound(new String("sounds/windHowl.mp3").split("/").join("."), new FLAKIT_ASSET$_531661301);
			Library.addSound(new String("sounds/footsteps-snow/step-2.mp3").split("/").join("."), new FLAKIT_ASSET$_1434075057);
			Library.addSound(new String("sounds/footsteps-snow/step-3.mp3").split("/").join("."), new FLAKIT_ASSET$_1797078961);
			Library.addSound(new String("sounds/footsteps-snow/step-4.mp3").split("/").join("."), new FLAKIT_ASSET$1292877903);
			Library.addSound(new String("sounds/footsteps-snow/step-5.mp3").split("/").join("."), new FLAKIT_ASSET$_1835745201);
			Library.addSound(new String("sounds/footsteps-snow/step.mp3").split("/").join("."), new FLAKIT_ASSET$_11183610);
			Library.addSound(new String("sounds/footsteps-hard/step-2.mp3").split("/").join("."), new FLAKIT_ASSET$_487780191);
			Library.addSound(new String("sounds/footsteps-hard/step-3.mp3").split("/").join("."), new FLAKIT_ASSET$_353890143);
			Library.addSound(new String("sounds/footsteps-hard/step.mp3").split("/").join("."), new FLAKIT_ASSET$_225120446);
			Library.addXML(new String("Library.xml").split("/").join("."), getXML(FLAKIT_ASSET$_1371418527));
			Library.addXML(new String("worlds/start/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$_475205487));
			Library.addXML(new String("worlds/snow-pond/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$1886460785));
			Library.addXML(new String("worlds/snow-hub/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$404816983));
			Library.addXML(new String("worlds/snow-basketball/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$2134780036));
			Library.addXML(new String("worlds/overworld/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$573320175));
			Library.addXML(new String("scripts/rotateWorld.xml").split("/").join("."), getXML(FLAKIT_ASSET$1821305064));
		}
		private function getXML(c:Class):XML{var d:ByteArray = new c;var s:String = d.readUTFBytes(d.length);return new XML(s);}
	}
}
