package
{
	import com.thaumaturgistgames.flakit.Library;
	import flash.utils.ByteArray;
	
	/**
	* Generated with LibraryBuilder for FLAKit
	* http://www.thaumaturgistgames.com/FLAKit
	*/
	public class EmbeddedAssets
	{
		[Embed(source = "../lib/ogmo/ambiance.png")] private const FLAKIT_ASSET$26896941:Class;
		[Embed(source = "../lib/ogmo/background.png")] private const FLAKIT_ASSET$_1157757234:Class;
		[Embed(source = "../lib/ogmo/camera.png")] private const FLAKIT_ASSET$_862204225:Class;
		[Embed(source = "../lib/ogmo/climate.png")] private const FLAKIT_ASSET$910413312:Class;
		[Embed(source = "../lib/ogmo/Decal.png")] private const FLAKIT_ASSET$338515033:Class;
		[Embed(source = "../lib/ogmo/director.png")] private const FLAKIT_ASSET$_1319427065:Class;
		[Embed(source = "../lib/ogmo/emitter.png")] private const FLAKIT_ASSET$_438935123:Class;
		[Embed(source = "../lib/ogmo/footsteps.png")] private const FLAKIT_ASSET$_1233139147:Class;
		[Embed(source = "../lib/ogmo/humphrey.png")] private const FLAKIT_ASSET$_1285077015:Class;
		[Embed(source = "../lib/ogmo/invitem.png")] private const FLAKIT_ASSET$_612164355:Class;
		[Embed(source = "../lib/ogmo/overworld.png")] private const FLAKIT_ASSET$_1221571681:Class;
		[Embed(source = "../lib/ogmo/script.png")] private const FLAKIT_ASSET$1622622818:Class;
		[Embed(source = "../lib/ogmo/smallhumphrey.png")] private const FLAKIT_ASSET$1909618802:Class;
		[Embed(source = "../lib/ogmo/soundtrack.png")] private const FLAKIT_ASSET$_1877960576:Class;
		[Embed(source = "../lib/ogmo/spinky.png")] private const FLAKIT_ASSET$_1448926885:Class;
		[Embed(source = "../lib/ogmo/star.png")] private const FLAKIT_ASSET$_904726580:Class;
		[Embed(source = "../lib/ogmo/train.png")] private const FLAKIT_ASSET$1362559242:Class;
		[Embed(source = "../lib/ogmo/worldreaction.png")] private const FLAKIT_ASSET$_386300015:Class;
		[Embed(source = "../lib/ogmo/worldSound.png")] private const FLAKIT_ASSET$1161070485:Class;
		[Embed(source = "../lib/art/thoughts/balloon-cost-abe.png")] private const FLAKIT_ASSET$_1385646596:Class;
		[Embed(source = "../lib/art/thoughts/balloon-cost-humphrey.png")] private const FLAKIT_ASSET$_665237024:Class;
		[Embed(source = "../lib/art/thoughts/basketball.png")] private const FLAKIT_ASSET$_1727928911:Class;
		[Embed(source = "../lib/art/thoughts/broken-heart.png")] private const FLAKIT_ASSET$1669660983:Class;
		[Embed(source = "../lib/art/thoughts/busy.png")] private const FLAKIT_ASSET$302548587:Class;
		[Embed(source = "../lib/art/thoughts/city.png")] private const FLAKIT_ASSET$_1402957145:Class;
		[Embed(source = "../lib/art/thoughts/coin.png")] private const FLAKIT_ASSET$_288522474:Class;
		[Embed(source = "../lib/art/thoughts/journal-frozen.png")] private const FLAKIT_ASSET$_1754430037:Class;
		[Embed(source = "../lib/art/thoughts/journal-thawed.png")] private const FLAKIT_ASSET$_1790088944:Class;
		[Embed(source = "../lib/art/thoughts/love.png")] private const FLAKIT_ASSET$808681005:Class;
		[Embed(source = "../lib/art/thoughts/rent-balloon.png")] private const FLAKIT_ASSET$_1697259187:Class;
		[Embed(source = "../lib/art/thoughts/ride-balloon.png")] private const FLAKIT_ASSET$_1335168587:Class;
		[Embed(source = "../lib/art/thoughts/spinky-crashed.png")] private const FLAKIT_ASSET$_761414494:Class;
		[Embed(source = "../lib/art/thoughts/spinky-flying.png")] private const FLAKIT_ASSET$1505902522:Class;
		[Embed(source = "../lib/art/thoughts/spinky-home.png")] private const FLAKIT_ASSET$1009045385:Class;
		[Embed(source = "../lib/art/thoughts/spinky-woods.png")] private const FLAKIT_ASSET$_225686997:Class;
		[Embed(source = "../lib/art/thoughts/surprise.png")] private const FLAKIT_ASSET$1261256846:Class;
		[Embed(source = "../lib/art/thoughts/where-spinky.png")] private const FLAKIT_ASSET$_460322063:Class;
		[Embed(source = "../lib/art/thoughts/woods.png")] private const FLAKIT_ASSET$_1538667977:Class;
		[Embed(source = "../lib/art/pickups/backpack.png")] private const FLAKIT_ASSET$_3860730:Class;
		[Embed(source = "../lib/art/pickups/desert-coin.png")] private const FLAKIT_ASSET$379953637:Class;
		[Embed(source = "../lib/art/pickups/journal.png")] private const FLAKIT_ASSET$_2032973506:Class;
		[Embed(source = "../lib/art/pickups/snow-coin.png")] private const FLAKIT_ASSET$_1581565778:Class;
		[Embed(source = "../lib/art/pickups/start-coin.png")] private const FLAKIT_ASSET$1324840388:Class;
		[Embed(source = "../lib/art/pickups/woods-coin.png")] private const FLAKIT_ASSET$_148402505:Class;
		[Embed(source = "../lib/art/particles/smoke.png")] private const FLAKIT_ASSET$_489507794:Class;
		[Embed(source = "../lib/art/particles/snowflake.png")] private const FLAKIT_ASSET$_430274975:Class;
		[Embed(source = "../lib/art/particles/water-sideways.png")] private const FLAKIT_ASSET$_1928805305:Class;
		[Embed(source = "../lib/art/particles/waterfall-sideways.png")] private const FLAKIT_ASSET$1580114083:Class;
		[Embed(source = "../lib/art/decals/balloon-platform.png")] private const FLAKIT_ASSET$_530865402:Class;
		[Embed(source = "../lib/art/decals/balloon.png")] private const FLAKIT_ASSET$_2066801113:Class;
		[Embed(source = "../lib/art/decals/chair.png")] private const FLAKIT_ASSET$2847401:Class;
		[Embed(source = "../lib/art/decals/city-hub.png")] private const FLAKIT_ASSET$1850880706:Class;
		[Embed(source = "../lib/art/decals/city-subway.png")] private const FLAKIT_ASSET$_1015891773:Class;
		[Embed(source = "../lib/art/decals/credits.png")] private const FLAKIT_ASSET$1651862713:Class;
		[Embed(source = "../lib/art/decals/desert-hub.png")] private const FLAKIT_ASSET$_1336183665:Class;
		[Embed(source = "../lib/art/decals/desert-sky.png")] private const FLAKIT_ASSET$_113216755:Class;
		[Embed(source = "../lib/art/decals/desert-subway.png")] private const FLAKIT_ASSET$1305127734:Class;
		[Embed(source = "../lib/art/decals/ice_block.png")] private const FLAKIT_ASSET$353445110:Class;
		[Embed(source = "../lib/art/decals/train.png")] private const FLAKIT_ASSET$_144019085:Class;
		[Embed(source = "../lib/art/decals/tree.png")] private const FLAKIT_ASSET$_1231354332:Class;
		[Embed(source = "../lib/art/characters/abe.png")] private const FLAKIT_ASSET$731243959:Class;
		[Embed(source = "../lib/art/characters/balloon.png")] private const FLAKIT_ASSET$1816571431:Class;
		[Embed(source = "../lib/art/characters/bluebird.png")] private const FLAKIT_ASSET$276152288:Class;
		[Embed(source = "../lib/art/characters/humphrey.png")] private const FLAKIT_ASSET$1976508815:Class;
		[Embed(source = "../lib/art/characters/owl.png")] private const FLAKIT_ASSET$916251404:Class;
		[Embed(source = "../lib/art/characters/robin.png")] private const FLAKIT_ASSET$761774246:Class;
		[Embed(source = "../lib/art/characters/spinky.png")] private const FLAKIT_ASSET$_591715485:Class;
		[Embed(source = "../lib/art/backgrounds/city-hub.png")] private const FLAKIT_ASSET$18517733:Class;
		[Embed(source = "../lib/art/backgrounds/city-subway.png")] private const FLAKIT_ASSET$_2145159630:Class;
		[Embed(source = "../lib/art/backgrounds/desert-subway.png")] private const FLAKIT_ASSET$2059294731:Class;
		[Embed(source = "../lib/art/backgrounds/overworld.png")] private const FLAKIT_ASSET$_1423972293:Class;
		[Embed(source = "../lib/art/backgrounds/snow-basketball.png")] private const FLAKIT_ASSET$_1317921299:Class;
		[Embed(source = "../lib/art/backgrounds/snow-hub.png")] private const FLAKIT_ASSET$_144923090:Class;
		[Embed(source = "../lib/art/backgrounds/snow-pond.png")] private const FLAKIT_ASSET$1743609987:Class;
		[Embed(source = "../lib/art/backgrounds/start.png")] private const FLAKIT_ASSET$_782423215:Class;
		[Embed(source = "../lib/art/backgrounds/subway-tunnel.png")] private const FLAKIT_ASSET$_1240464983:Class;
		[Embed(source = "../lib/art/backgrounds/title.png")] private const FLAKIT_ASSET$1152694783:Class;
		[Embed(source = "../lib/art/backgrounds/woods-gate.png")] private const FLAKIT_ASSET$_585748117:Class;
		[Embed(source = "../lib/art/backgrounds/woods-waterfall.png")] private const FLAKIT_ASSET$971346937:Class;
		[Embed(source = "../lib/sounds/crickets.mp3")] private const FLAKIT_ASSET$_451768168:Class;
		[Embed(source = "../lib/sounds/river.mp3")] private const FLAKIT_ASSET$337606672:Class;
		[Embed(source = "../lib/sounds/subway.mp3")] private const FLAKIT_ASSET$_1939745910:Class;
		[Embed(source = "../lib/sounds/traffic.mp3")] private const FLAKIT_ASSET$339336096:Class;
		[Embed(source = "../lib/sounds/windHowl.mp3")] private const FLAKIT_ASSET$_531661301:Class;
		[Embed(source = "../lib/sounds/music/desert.mp3")] private const FLAKIT_ASSET$_284577292:Class;
		[Embed(source = "../lib/sounds/music/draft-city_HTAR.mp3")] private const FLAKIT_ASSET$_1488486009:Class;
		[Embed(source = "../lib/sounds/music/ending.mp3")] private const FLAKIT_ASSET$718291522:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-2.mp3")] private const FLAKIT_ASSET$_1434075057:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-3.mp3")] private const FLAKIT_ASSET$_1797078961:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-4.mp3")] private const FLAKIT_ASSET$1292877903:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-5.mp3")] private const FLAKIT_ASSET$_1835745201:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step.mp3")] private const FLAKIT_ASSET$_11183610:Class;
		[Embed(source = "../lib/sounds/footsteps-sand/step.mp3")] private const FLAKIT_ASSET$_1526623850:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step-2.mp3")] private const FLAKIT_ASSET$_487780191:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step-3.mp3")] private const FLAKIT_ASSET$_353890143:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step.mp3")] private const FLAKIT_ASSET$_225120446:Class;
		[Embed(source = "../lib/sounds/footsteps-dirt/step-1.mp3")] private const FLAKIT_ASSET$_1018750609:Class;
		[Embed(source = "../lib/sounds/footsteps-dirt/step-2.mp3")] private const FLAKIT_ASSET$2109872495:Class;
		[Embed(source = "../lib/sounds/footsteps-dirt/step-3.mp3")] private const FLAKIT_ASSET$_2051204753:Class;
		[Embed(source = "../lib/sounds/footsteps-dirt/step-4.mp3")] private const FLAKIT_ASSET$_1688200849:Class;
		[Embed(source = "../lib/sounds/footsteps-dirt/step.mp3")] private const FLAKIT_ASSET$418678756:Class;
		[Embed(source = "../lib/Library.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_1371418527:Class;
		[Embed(source = "../lib/worlds/woods-river/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$2108018679:Class;
		[Embed(source = "../lib/worlds/woods-gate/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_250403341:Class;
		[Embed(source = "../lib/worlds/title/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_110921121:Class;
		[Embed(source = "../lib/worlds/start/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_475205487:Class;
		[Embed(source = "../lib/worlds/snow-pond/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1886460785:Class;
		[Embed(source = "../lib/worlds/snow-hub/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$404816983:Class;
		[Embed(source = "../lib/worlds/snow-basketball/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$2134780036:Class;
		[Embed(source = "../lib/worlds/overworld/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$573320175:Class;
		[Embed(source = "../lib/worlds/desert-subway/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_926514661:Class;
		[Embed(source = "../lib/worlds/desert-hub/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$818774959:Class;
		[Embed(source = "../lib/worlds/city-subway/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1375485504:Class;
		[Embed(source = "../lib/worlds/city-hub/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$285960271:Class;
		[Embed(source = "../lib/scripts/rotateWorld.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1821305064:Class;
		[Embed(source = "../lib/scripts/title.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_159897647:Class;
		[Embed(source = "../lib/scripts/woods/birds-story.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1768220113:Class;
		[Embed(source = "../lib/scripts/woods/birds.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$123616298:Class;
		[Embed(source = "../lib/scripts/woods/humphrey-question.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$153531525:Class;
		[Embed(source = "../lib/scripts/woods/owl-story.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$452442009:Class;
		[Embed(source = "../lib/scripts/start/opening-cutscene-humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$71002295:Class;
		[Embed(source = "../lib/scripts/start/opening-cutscene-spinky.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1970101167:Class;
		[Embed(source = "../lib/scripts/start/opening-cutscene.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_2002895077:Class;
		[Embed(source = "../lib/scripts/snow/find-journal-humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_946644895:Class;
		[Embed(source = "../lib/scripts/snow/find-journal.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_1420615381:Class;
		[Embed(source = "../lib/scripts/desert/humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_2034307163:Class;
		[Embed(source = "../lib/scripts/desert/thaw-journal.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$2133243993:Class;
		[Embed(source = "../lib/scripts/coins/desert-coin-humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1584097612:Class;
		[Embed(source = "../lib/scripts/coins/desert-coin.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1978405614:Class;
		[Embed(source = "../lib/scripts/coins/snow-coin-humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1601849988:Class;
		[Embed(source = "../lib/scripts/coins/snow-coin.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1294536187:Class;
		[Embed(source = "../lib/scripts/coins/woods-coin-humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$783697359:Class;
		[Embed(source = "../lib/scripts/coins/woods-coin.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_835554929:Class;
		[Embed(source = "../lib/scripts/city/abe-more-money.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_536610461:Class;
		[Embed(source = "../lib/scripts/city/abe-rent-balloon.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$811976665:Class;
		[Embed(source = "../lib/scripts/city/humphrey-ride-balloon.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1488757975:Class;
		[Embed(source = "../lib/scripts/city/rent-balloon.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1358115919:Class;
		[Embed(source = "../lib/config/settings.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_901571473:Class;
		
		public function EmbeddedAssets()
		{
			Library.addImage(new String("ogmo/ambiance.png").split("/").join("."), new FLAKIT_ASSET$26896941);
			Library.addImage(new String("ogmo/background.png").split("/").join("."), new FLAKIT_ASSET$_1157757234);
			Library.addImage(new String("ogmo/camera.png").split("/").join("."), new FLAKIT_ASSET$_862204225);
			Library.addImage(new String("ogmo/climate.png").split("/").join("."), new FLAKIT_ASSET$910413312);
			Library.addImage(new String("ogmo/Decal.png").split("/").join("."), new FLAKIT_ASSET$338515033);
			Library.addImage(new String("ogmo/director.png").split("/").join("."), new FLAKIT_ASSET$_1319427065);
			Library.addImage(new String("ogmo/emitter.png").split("/").join("."), new FLAKIT_ASSET$_438935123);
			Library.addImage(new String("ogmo/footsteps.png").split("/").join("."), new FLAKIT_ASSET$_1233139147);
			Library.addImage(new String("ogmo/humphrey.png").split("/").join("."), new FLAKIT_ASSET$_1285077015);
			Library.addImage(new String("ogmo/invitem.png").split("/").join("."), new FLAKIT_ASSET$_612164355);
			Library.addImage(new String("ogmo/overworld.png").split("/").join("."), new FLAKIT_ASSET$_1221571681);
			Library.addImage(new String("ogmo/script.png").split("/").join("."), new FLAKIT_ASSET$1622622818);
			Library.addImage(new String("ogmo/smallhumphrey.png").split("/").join("."), new FLAKIT_ASSET$1909618802);
			Library.addImage(new String("ogmo/soundtrack.png").split("/").join("."), new FLAKIT_ASSET$_1877960576);
			Library.addImage(new String("ogmo/spinky.png").split("/").join("."), new FLAKIT_ASSET$_1448926885);
			Library.addImage(new String("ogmo/star.png").split("/").join("."), new FLAKIT_ASSET$_904726580);
			Library.addImage(new String("ogmo/train.png").split("/").join("."), new FLAKIT_ASSET$1362559242);
			Library.addImage(new String("ogmo/worldreaction.png").split("/").join("."), new FLAKIT_ASSET$_386300015);
			Library.addImage(new String("ogmo/worldSound.png").split("/").join("."), new FLAKIT_ASSET$1161070485);
			Library.addImage(new String("art/thoughts/balloon-cost-abe.png").split("/").join("."), new FLAKIT_ASSET$_1385646596);
			Library.addImage(new String("art/thoughts/balloon-cost-humphrey.png").split("/").join("."), new FLAKIT_ASSET$_665237024);
			Library.addImage(new String("art/thoughts/basketball.png").split("/").join("."), new FLAKIT_ASSET$_1727928911);
			Library.addImage(new String("art/thoughts/broken-heart.png").split("/").join("."), new FLAKIT_ASSET$1669660983);
			Library.addImage(new String("art/thoughts/busy.png").split("/").join("."), new FLAKIT_ASSET$302548587);
			Library.addImage(new String("art/thoughts/city.png").split("/").join("."), new FLAKIT_ASSET$_1402957145);
			Library.addImage(new String("art/thoughts/coin.png").split("/").join("."), new FLAKIT_ASSET$_288522474);
			Library.addImage(new String("art/thoughts/journal-frozen.png").split("/").join("."), new FLAKIT_ASSET$_1754430037);
			Library.addImage(new String("art/thoughts/journal-thawed.png").split("/").join("."), new FLAKIT_ASSET$_1790088944);
			Library.addImage(new String("art/thoughts/love.png").split("/").join("."), new FLAKIT_ASSET$808681005);
			Library.addImage(new String("art/thoughts/rent-balloon.png").split("/").join("."), new FLAKIT_ASSET$_1697259187);
			Library.addImage(new String("art/thoughts/ride-balloon.png").split("/").join("."), new FLAKIT_ASSET$_1335168587);
			Library.addImage(new String("art/thoughts/spinky-crashed.png").split("/").join("."), new FLAKIT_ASSET$_761414494);
			Library.addImage(new String("art/thoughts/spinky-flying.png").split("/").join("."), new FLAKIT_ASSET$1505902522);
			Library.addImage(new String("art/thoughts/spinky-home.png").split("/").join("."), new FLAKIT_ASSET$1009045385);
			Library.addImage(new String("art/thoughts/spinky-woods.png").split("/").join("."), new FLAKIT_ASSET$_225686997);
			Library.addImage(new String("art/thoughts/surprise.png").split("/").join("."), new FLAKIT_ASSET$1261256846);
			Library.addImage(new String("art/thoughts/where-spinky.png").split("/").join("."), new FLAKIT_ASSET$_460322063);
			Library.addImage(new String("art/thoughts/woods.png").split("/").join("."), new FLAKIT_ASSET$_1538667977);
			Library.addImage(new String("art/pickups/backpack.png").split("/").join("."), new FLAKIT_ASSET$_3860730);
			Library.addImage(new String("art/pickups/desert-coin.png").split("/").join("."), new FLAKIT_ASSET$379953637);
			Library.addImage(new String("art/pickups/journal.png").split("/").join("."), new FLAKIT_ASSET$_2032973506);
			Library.addImage(new String("art/pickups/snow-coin.png").split("/").join("."), new FLAKIT_ASSET$_1581565778);
			Library.addImage(new String("art/pickups/start-coin.png").split("/").join("."), new FLAKIT_ASSET$1324840388);
			Library.addImage(new String("art/pickups/woods-coin.png").split("/").join("."), new FLAKIT_ASSET$_148402505);
			Library.addImage(new String("art/particles/smoke.png").split("/").join("."), new FLAKIT_ASSET$_489507794);
			Library.addImage(new String("art/particles/snowflake.png").split("/").join("."), new FLAKIT_ASSET$_430274975);
			Library.addImage(new String("art/particles/water-sideways.png").split("/").join("."), new FLAKIT_ASSET$_1928805305);
			Library.addImage(new String("art/particles/waterfall-sideways.png").split("/").join("."), new FLAKIT_ASSET$1580114083);
			Library.addImage(new String("art/decals/balloon-platform.png").split("/").join("."), new FLAKIT_ASSET$_530865402);
			Library.addImage(new String("art/decals/balloon.png").split("/").join("."), new FLAKIT_ASSET$_2066801113);
			Library.addImage(new String("art/decals/chair.png").split("/").join("."), new FLAKIT_ASSET$2847401);
			Library.addImage(new String("art/decals/city-hub.png").split("/").join("."), new FLAKIT_ASSET$1850880706);
			Library.addImage(new String("art/decals/city-subway.png").split("/").join("."), new FLAKIT_ASSET$_1015891773);
			Library.addImage(new String("art/decals/credits.png").split("/").join("."), new FLAKIT_ASSET$1651862713);
			Library.addImage(new String("art/decals/desert-hub.png").split("/").join("."), new FLAKIT_ASSET$_1336183665);
			Library.addImage(new String("art/decals/desert-sky.png").split("/").join("."), new FLAKIT_ASSET$_113216755);
			Library.addImage(new String("art/decals/desert-subway.png").split("/").join("."), new FLAKIT_ASSET$1305127734);
			Library.addImage(new String("art/decals/ice_block.png").split("/").join("."), new FLAKIT_ASSET$353445110);
			Library.addImage(new String("art/decals/train.png").split("/").join("."), new FLAKIT_ASSET$_144019085);
			Library.addImage(new String("art/decals/tree.png").split("/").join("."), new FLAKIT_ASSET$_1231354332);
			Library.addImage(new String("art/characters/abe.png").split("/").join("."), new FLAKIT_ASSET$731243959);
			Library.addImage(new String("art/characters/balloon.png").split("/").join("."), new FLAKIT_ASSET$1816571431);
			Library.addImage(new String("art/characters/bluebird.png").split("/").join("."), new FLAKIT_ASSET$276152288);
			Library.addImage(new String("art/characters/humphrey.png").split("/").join("."), new FLAKIT_ASSET$1976508815);
			Library.addImage(new String("art/characters/owl.png").split("/").join("."), new FLAKIT_ASSET$916251404);
			Library.addImage(new String("art/characters/robin.png").split("/").join("."), new FLAKIT_ASSET$761774246);
			Library.addImage(new String("art/characters/spinky.png").split("/").join("."), new FLAKIT_ASSET$_591715485);
			Library.addImage(new String("art/backgrounds/city-hub.png").split("/").join("."), new FLAKIT_ASSET$18517733);
			Library.addImage(new String("art/backgrounds/city-subway.png").split("/").join("."), new FLAKIT_ASSET$_2145159630);
			Library.addImage(new String("art/backgrounds/desert-subway.png").split("/").join("."), new FLAKIT_ASSET$2059294731);
			Library.addImage(new String("art/backgrounds/overworld.png").split("/").join("."), new FLAKIT_ASSET$_1423972293);
			Library.addImage(new String("art/backgrounds/snow-basketball.png").split("/").join("."), new FLAKIT_ASSET$_1317921299);
			Library.addImage(new String("art/backgrounds/snow-hub.png").split("/").join("."), new FLAKIT_ASSET$_144923090);
			Library.addImage(new String("art/backgrounds/snow-pond.png").split("/").join("."), new FLAKIT_ASSET$1743609987);
			Library.addImage(new String("art/backgrounds/start.png").split("/").join("."), new FLAKIT_ASSET$_782423215);
			Library.addImage(new String("art/backgrounds/subway-tunnel.png").split("/").join("."), new FLAKIT_ASSET$_1240464983);
			Library.addImage(new String("art/backgrounds/title.png").split("/").join("."), new FLAKIT_ASSET$1152694783);
			Library.addImage(new String("art/backgrounds/woods-gate.png").split("/").join("."), new FLAKIT_ASSET$_585748117);
			Library.addImage(new String("art/backgrounds/woods-waterfall.png").split("/").join("."), new FLAKIT_ASSET$971346937);
			Library.addSound(new String("sounds/crickets.mp3").split("/").join("."), new FLAKIT_ASSET$_451768168);
			Library.addSound(new String("sounds/river.mp3").split("/").join("."), new FLAKIT_ASSET$337606672);
			Library.addSound(new String("sounds/subway.mp3").split("/").join("."), new FLAKIT_ASSET$_1939745910);
			Library.addSound(new String("sounds/traffic.mp3").split("/").join("."), new FLAKIT_ASSET$339336096);
			Library.addSound(new String("sounds/windHowl.mp3").split("/").join("."), new FLAKIT_ASSET$_531661301);
			Library.addSound(new String("sounds/music/desert.mp3").split("/").join("."), new FLAKIT_ASSET$_284577292);
			Library.addSound(new String("sounds/music/draft-city_HTAR.mp3").split("/").join("."), new FLAKIT_ASSET$_1488486009);
			Library.addSound(new String("sounds/music/ending.mp3").split("/").join("."), new FLAKIT_ASSET$718291522);
			Library.addSound(new String("sounds/footsteps-snow/step-2.mp3").split("/").join("."), new FLAKIT_ASSET$_1434075057);
			Library.addSound(new String("sounds/footsteps-snow/step-3.mp3").split("/").join("."), new FLAKIT_ASSET$_1797078961);
			Library.addSound(new String("sounds/footsteps-snow/step-4.mp3").split("/").join("."), new FLAKIT_ASSET$1292877903);
			Library.addSound(new String("sounds/footsteps-snow/step-5.mp3").split("/").join("."), new FLAKIT_ASSET$_1835745201);
			Library.addSound(new String("sounds/footsteps-snow/step.mp3").split("/").join("."), new FLAKIT_ASSET$_11183610);
			Library.addSound(new String("sounds/footsteps-sand/step.mp3").split("/").join("."), new FLAKIT_ASSET$_1526623850);
			Library.addSound(new String("sounds/footsteps-hard/step-2.mp3").split("/").join("."), new FLAKIT_ASSET$_487780191);
			Library.addSound(new String("sounds/footsteps-hard/step-3.mp3").split("/").join("."), new FLAKIT_ASSET$_353890143);
			Library.addSound(new String("sounds/footsteps-hard/step.mp3").split("/").join("."), new FLAKIT_ASSET$_225120446);
			Library.addSound(new String("sounds/footsteps-dirt/step-1.mp3").split("/").join("."), new FLAKIT_ASSET$_1018750609);
			Library.addSound(new String("sounds/footsteps-dirt/step-2.mp3").split("/").join("."), new FLAKIT_ASSET$2109872495);
			Library.addSound(new String("sounds/footsteps-dirt/step-3.mp3").split("/").join("."), new FLAKIT_ASSET$_2051204753);
			Library.addSound(new String("sounds/footsteps-dirt/step-4.mp3").split("/").join("."), new FLAKIT_ASSET$_1688200849);
			Library.addSound(new String("sounds/footsteps-dirt/step.mp3").split("/").join("."), new FLAKIT_ASSET$418678756);
			Library.addXML(new String("Library.xml").split("/").join("."), getXML(FLAKIT_ASSET$_1371418527));
			Library.addXML(new String("worlds/woods-river/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$2108018679));
			Library.addXML(new String("worlds/woods-gate/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$_250403341));
			Library.addXML(new String("worlds/title/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$_110921121));
			Library.addXML(new String("worlds/start/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$_475205487));
			Library.addXML(new String("worlds/snow-pond/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$1886460785));
			Library.addXML(new String("worlds/snow-hub/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$404816983));
			Library.addXML(new String("worlds/snow-basketball/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$2134780036));
			Library.addXML(new String("worlds/overworld/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$573320175));
			Library.addXML(new String("worlds/desert-subway/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$_926514661));
			Library.addXML(new String("worlds/desert-hub/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$818774959));
			Library.addXML(new String("worlds/city-subway/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$1375485504));
			Library.addXML(new String("worlds/city-hub/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$285960271));
			Library.addXML(new String("scripts/rotateWorld.xml").split("/").join("."), getXML(FLAKIT_ASSET$1821305064));
			Library.addXML(new String("scripts/title.xml").split("/").join("."), getXML(FLAKIT_ASSET$_159897647));
			Library.addXML(new String("scripts/woods/birds-story.xml").split("/").join("."), getXML(FLAKIT_ASSET$1768220113));
			Library.addXML(new String("scripts/woods/birds.xml").split("/").join("."), getXML(FLAKIT_ASSET$123616298));
			Library.addXML(new String("scripts/woods/humphrey-question.xml").split("/").join("."), getXML(FLAKIT_ASSET$153531525));
			Library.addXML(new String("scripts/woods/owl-story.xml").split("/").join("."), getXML(FLAKIT_ASSET$452442009));
			Library.addXML(new String("scripts/start/opening-cutscene-humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$71002295));
			Library.addXML(new String("scripts/start/opening-cutscene-spinky.xml").split("/").join("."), getXML(FLAKIT_ASSET$1970101167));
			Library.addXML(new String("scripts/start/opening-cutscene.xml").split("/").join("."), getXML(FLAKIT_ASSET$_2002895077));
			Library.addXML(new String("scripts/snow/find-journal-humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$_946644895));
			Library.addXML(new String("scripts/snow/find-journal.xml").split("/").join("."), getXML(FLAKIT_ASSET$_1420615381));
			Library.addXML(new String("scripts/desert/humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$_2034307163));
			Library.addXML(new String("scripts/desert/thaw-journal.xml").split("/").join("."), getXML(FLAKIT_ASSET$2133243993));
			Library.addXML(new String("scripts/coins/desert-coin-humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$1584097612));
			Library.addXML(new String("scripts/coins/desert-coin.xml").split("/").join("."), getXML(FLAKIT_ASSET$1978405614));
			Library.addXML(new String("scripts/coins/snow-coin-humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$1601849988));
			Library.addXML(new String("scripts/coins/snow-coin.xml").split("/").join("."), getXML(FLAKIT_ASSET$1294536187));
			Library.addXML(new String("scripts/coins/woods-coin-humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$783697359));
			Library.addXML(new String("scripts/coins/woods-coin.xml").split("/").join("."), getXML(FLAKIT_ASSET$_835554929));
			Library.addXML(new String("scripts/city/abe-more-money.xml").split("/").join("."), getXML(FLAKIT_ASSET$_536610461));
			Library.addXML(new String("scripts/city/abe-rent-balloon.xml").split("/").join("."), getXML(FLAKIT_ASSET$811976665));
			Library.addXML(new String("scripts/city/humphrey-ride-balloon.xml").split("/").join("."), getXML(FLAKIT_ASSET$1488757975));
			Library.addXML(new String("scripts/city/rent-balloon.xml").split("/").join("."), getXML(FLAKIT_ASSET$1358115919));
			Library.addXML(new String("config/settings.xml").split("/").join("."), getXML(FLAKIT_ASSET$_901571473));
		}
		private function getXML(c:Class):XML{var d:ByteArray = new c;var s:String = d.readUTFBytes(d.length);return new XML(s);}
	}
}
