package
{
	import com.thaumaturgistgames.flakit.Library;
	import flash.utils.ByteArray;
	
	/**
	* Generated with LibraryBuilder for FLAKit
	* http://www.thaumaturgistgames.com/FLAKit
	*/
	public class EmbeddedAssets
	{
		[Embed(source = "../lib/originals/spinky_poses.png")] private const FLAKIT_ASSET$696558064:Class;
		[Embed(source = "../lib/originals/thought_backpack.png")] private const FLAKIT_ASSET$1994845725:Class;
		[Embed(source = "../lib/originals/thought_heat.png")] private const FLAKIT_ASSET$1664016575:Class;
		[Embed(source = "../lib/originals/Scene 1/backpack.png")] private const FLAKIT_ASSET$_905261481:Class;
		[Embed(source = "../lib/originals/Scene 1/chair.png")] private const FLAKIT_ASSET$80534841:Class;
		[Embed(source = "../lib/originals/Scene 1/humphrey_sitting.png")] private const FLAKIT_ASSET$_1775862718:Class;
		[Embed(source = "../lib/originals/Scene 1/scene1.png")] private const FLAKIT_ASSET$_943239816:Class;
		[Embed(source = "../lib/originals/Scene 1/thought_play.png")] private const FLAKIT_ASSET$_1101732393:Class;
		[Embed(source = "../lib/originals/Scene 1/thought_where_spinky.png")] private const FLAKIT_ASSET$661925451:Class;
		[Embed(source = "../lib/originals/Scene 1/thought_work.png")] private const FLAKIT_ASSET$_114963643:Class;
		[Embed(source = "../lib/originals/Scene 1/thought_worry.png")] private const FLAKIT_ASSET$_1339359349:Class;
		[Embed(source = "../lib/originals/forest/bluejay.png")] private const FLAKIT_ASSET$867857076:Class;
		[Embed(source = "../lib/originals/forest/forest.png")] private const FLAKIT_ASSET$_1857407619:Class;
		[Embed(source = "../lib/originals/forest/owl.png")] private const FLAKIT_ASSET$1195382361:Class;
		[Embed(source = "../lib/originals/forest/robin.png")] private const FLAKIT_ASSET$_992673407:Class;
		[Embed(source = "../lib/originals/forest/THOUGHT_ICE.PNG")] private const FLAKIT_ASSET$1051328945:Class;
		[Embed(source = "../lib/originals/forest/THOUGHT_SPINKY_CRASH.PNG")] private const FLAKIT_ASSET$1307309286:Class;
		[Embed(source = "../lib/originals/forest/THOUGHT_SPINKY_TRY_FLY.PNG")] private const FLAKIT_ASSET$279417711:Class;
		[Embed(source = "../lib/originals/desert/desert.png")] private const FLAKIT_ASSET$_1085353871:Class;
		[Embed(source = "../lib/originals/desert/HAND_JOURNAL.PNG")] private const FLAKIT_ASSET$_222617567:Class;
		[Embed(source = "../lib/originals/desert/thought_alert_melt.png")] private const FLAKIT_ASSET$983665735:Class;
		[Embed(source = "../lib/originals/desert/thought_city.png")] private const FLAKIT_ASSET$2082608830:Class;
		[Embed(source = "../lib/originals/city/balloon_guy.png")] private const FLAKIT_ASSET$_1570858312:Class;
		[Embed(source = "../lib/originals/city/city.png")] private const FLAKIT_ASSET$454275398:Class;
		[Embed(source = "../lib/originals/city/cop.png")] private const FLAKIT_ASSET$546988608:Class;
		[Embed(source = "../lib/originals/city/no_exit.png")] private const FLAKIT_ASSET$1271420847:Class;
		[Embed(source = "../lib/originals/city/no_penguins.png")] private const FLAKIT_ASSET$_401733363:Class;
		[Embed(source = "../lib/originals/city/thought_forest.png")] private const FLAKIT_ASSET$985093860:Class;
		[Embed(source = "../lib/originals/city/thought_no_exit.png")] private const FLAKIT_ASSET$41517448:Class;
		[Embed(source = "../lib/originals/city/thought_no_penguins.png")] private const FLAKIT_ASSET$_2096841785:Class;
		[Embed(source = "../lib/originals/city/thought_penguin_balloon.png")] private const FLAKIT_ASSET$_913814127:Class;
		[Embed(source = "../lib/originals/city/thought_penguin_balloon_guy.png")] private const FLAKIT_ASSET$532174220:Class;
		[Embed(source = "../lib/ogmo/ambiance.png")] private const FLAKIT_ASSET$26896941:Class;
		[Embed(source = "../lib/ogmo/background.png")] private const FLAKIT_ASSET$_1157757234:Class;
		[Embed(source = "../lib/ogmo/camera.png")] private const FLAKIT_ASSET$_862204225:Class;
		[Embed(source = "../lib/ogmo/climate.png")] private const FLAKIT_ASSET$910413312:Class;
		[Embed(source = "../lib/ogmo/Decal.png")] private const FLAKIT_ASSET$338515033:Class;
		[Embed(source = "../lib/ogmo/director.png")] private const FLAKIT_ASSET$_1319427065:Class;
		[Embed(source = "../lib/ogmo/emitter.png")] private const FLAKIT_ASSET$_438935123:Class;
		[Embed(source = "../lib/ogmo/footsteps.png")] private const FLAKIT_ASSET$_1233139147:Class;
		[Embed(source = "../lib/ogmo/humphrey.png")] private const FLAKIT_ASSET$_1285077015:Class;
		[Embed(source = "../lib/ogmo/invitem.png")] private const FLAKIT_ASSET$_612164355:Class;
		[Embed(source = "../lib/ogmo/overworld.png")] private const FLAKIT_ASSET$_1221571681:Class;
		[Embed(source = "../lib/ogmo/script.png")] private const FLAKIT_ASSET$1622622818:Class;
		[Embed(source = "../lib/ogmo/smallhumphrey.png")] private const FLAKIT_ASSET$1909618802:Class;
		[Embed(source = "../lib/ogmo/worldreaction.png")] private const FLAKIT_ASSET$_386300015:Class;
		[Embed(source = "../lib/ogmo/worldSound.png")] private const FLAKIT_ASSET$1161070485:Class;
		[Embed(source = "../lib/art/thoughts/coin.png")] private const FLAKIT_ASSET$_288522474:Class;
		[Embed(source = "../lib/art/snow/snowdrift.png")] private const FLAKIT_ASSET$360635201:Class;
		[Embed(source = "../lib/art/snow/snowflake.png")] private const FLAKIT_ASSET$1532032240:Class;
		[Embed(source = "../lib/art/snow/snow_exterior.png")] private const FLAKIT_ASSET$_1731975245:Class;
		[Embed(source = "../lib/art/snow/thought_big_heart.png")] private const FLAKIT_ASSET$1026734727:Class;
		[Embed(source = "../lib/art/snow/thought_small_heart.png")] private const FLAKIT_ASSET$520857850:Class;
		[Embed(source = "../lib/art/pickups/backpack.png")] private const FLAKIT_ASSET$_3860730:Class;
		[Embed(source = "../lib/art/pickups/desert-coin.png")] private const FLAKIT_ASSET$379953637:Class;
		[Embed(source = "../lib/art/pickups/journal.png")] private const FLAKIT_ASSET$_2032973506:Class;
		[Embed(source = "../lib/art/pickups/start-coin.png")] private const FLAKIT_ASSET$1324840388:Class;
		[Embed(source = "../lib/art/pickups/woods-coin.png")] private const FLAKIT_ASSET$_148402505:Class;
		[Embed(source = "../lib/art/particles/flame_01.png")] private const FLAKIT_ASSET$_1946428317:Class;
		[Embed(source = "../lib/art/particles/flame_02.png")] private const FLAKIT_ASSET$_1956717469:Class;
		[Embed(source = "../lib/art/particles/flame_03.png")] private const FLAKIT_ASSET$_1958880157:Class;
		[Embed(source = "../lib/art/particles/smoke.png")] private const FLAKIT_ASSET$_489507794:Class;
		[Embed(source = "../lib/art/particles/snowflake.png")] private const FLAKIT_ASSET$_430274975:Class;
		[Embed(source = "../lib/art/decals/balloon-platform.png")] private const FLAKIT_ASSET$_530865402:Class;
		[Embed(source = "../lib/art/decals/balloon.png")] private const FLAKIT_ASSET$_2066801113:Class;
		[Embed(source = "../lib/art/decals/chair.png")] private const FLAKIT_ASSET$2847401:Class;
		[Embed(source = "../lib/art/decals/city-hub.png")] private const FLAKIT_ASSET$1850880706:Class;
		[Embed(source = "../lib/art/decals/city-subway.png")] private const FLAKIT_ASSET$_1015891773:Class;
		[Embed(source = "../lib/art/decals/desert-hub.png")] private const FLAKIT_ASSET$_1336183665:Class;
		[Embed(source = "../lib/art/decals/desert-sky.png")] private const FLAKIT_ASSET$_113216755:Class;
		[Embed(source = "../lib/art/decals/desert-subway.png")] private const FLAKIT_ASSET$1305127734:Class;
		[Embed(source = "../lib/art/decals/ice_block.png")] private const FLAKIT_ASSET$353445110:Class;
		[Embed(source = "../lib/art/characters/abe.png")] private const FLAKIT_ASSET$731243959:Class;
		[Embed(source = "../lib/art/characters/humphrey.png")] private const FLAKIT_ASSET$1976508815:Class;
		[Embed(source = "../lib/art/backgrounds/city-hub.png")] private const FLAKIT_ASSET$18517733:Class;
		[Embed(source = "../lib/art/backgrounds/overworld.png")] private const FLAKIT_ASSET$_1423972293:Class;
		[Embed(source = "../lib/art/backgrounds/snow-basketball.png")] private const FLAKIT_ASSET$_1317921299:Class;
		[Embed(source = "../lib/art/backgrounds/snow-hub.png")] private const FLAKIT_ASSET$_144923090:Class;
		[Embed(source = "../lib/art/backgrounds/snow-pond.png")] private const FLAKIT_ASSET$1743609987:Class;
		[Embed(source = "../lib/art/backgrounds/start.png")] private const FLAKIT_ASSET$_782423215:Class;
		[Embed(source = "../lib/art/backgrounds/woods-gate.png")] private const FLAKIT_ASSET$_585748117:Class;
		[Embed(source = "../lib/sounds/crickets.mp3")] private const FLAKIT_ASSET$_451768168:Class;
		[Embed(source = "../lib/sounds/traffic.mp3")] private const FLAKIT_ASSET$339336096:Class;
		[Embed(source = "../lib/sounds/windHowl.mp3")] private const FLAKIT_ASSET$_531661301:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-2.mp3")] private const FLAKIT_ASSET$_1434075057:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-3.mp3")] private const FLAKIT_ASSET$_1797078961:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-4.mp3")] private const FLAKIT_ASSET$1292877903:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step-5.mp3")] private const FLAKIT_ASSET$_1835745201:Class;
		[Embed(source = "../lib/sounds/footsteps-snow/step.mp3")] private const FLAKIT_ASSET$_11183610:Class;
		[Embed(source = "../lib/sounds/footsteps-sand/step.mp3")] private const FLAKIT_ASSET$_1526623850:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step-2.mp3")] private const FLAKIT_ASSET$_487780191:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step-3.mp3")] private const FLAKIT_ASSET$_353890143:Class;
		[Embed(source = "../lib/sounds/footsteps-hard/step.mp3")] private const FLAKIT_ASSET$_225120446:Class;
		[Embed(source = "../lib/Library.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_1371418527:Class;
		[Embed(source = "../lib/worlds/woods-gate/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_250403341:Class;
		[Embed(source = "../lib/worlds/start/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_475205487:Class;
		[Embed(source = "../lib/worlds/snow-pond/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1886460785:Class;
		[Embed(source = "../lib/worlds/snow-hub/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$404816983:Class;
		[Embed(source = "../lib/worlds/snow-basketball/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$2134780036:Class;
		[Embed(source = "../lib/worlds/overworld/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$573320175:Class;
		[Embed(source = "../lib/worlds/desert-hub/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$818774959:Class;
		[Embed(source = "../lib/worlds/city-hub/map.oel", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$285960271:Class;
		[Embed(source = "../lib/scripts/desert-coin-humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_897355116:Class;
		[Embed(source = "../lib/scripts/desert-coin.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$911999451:Class;
		[Embed(source = "../lib/scripts/rotateWorld.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1821305064:Class;
		[Embed(source = "../lib/scripts/start-coin-humphrey.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_623559228:Class;
		[Embed(source = "../lib/scripts/start-coin.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_1949650226:Class;
		[Embed(source = "../lib/scripts/old/abe-test.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$1897969838:Class;
		[Embed(source = "../lib/scripts/old/city-hub.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_431966461:Class;
		[Embed(source = "../lib/scripts/old/humphrey-actions-start.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$445936569:Class;
		[Embed(source = "../lib/config/settings.xml", mimeType = "application/octet-stream")] private const FLAKIT_ASSET$_901571473:Class;
		
		public function EmbeddedAssets()
		{
			Library.addImage(new String("originals/spinky_poses.png").split("/").join("."), new FLAKIT_ASSET$696558064);
			Library.addImage(new String("originals/thought_backpack.png").split("/").join("."), new FLAKIT_ASSET$1994845725);
			Library.addImage(new String("originals/thought_heat.png").split("/").join("."), new FLAKIT_ASSET$1664016575);
			Library.addImage(new String("originals/Scene 1/backpack.png").split("/").join("."), new FLAKIT_ASSET$_905261481);
			Library.addImage(new String("originals/Scene 1/chair.png").split("/").join("."), new FLAKIT_ASSET$80534841);
			Library.addImage(new String("originals/Scene 1/humphrey_sitting.png").split("/").join("."), new FLAKIT_ASSET$_1775862718);
			Library.addImage(new String("originals/Scene 1/scene1.png").split("/").join("."), new FLAKIT_ASSET$_943239816);
			Library.addImage(new String("originals/Scene 1/thought_play.png").split("/").join("."), new FLAKIT_ASSET$_1101732393);
			Library.addImage(new String("originals/Scene 1/thought_where_spinky.png").split("/").join("."), new FLAKIT_ASSET$661925451);
			Library.addImage(new String("originals/Scene 1/thought_work.png").split("/").join("."), new FLAKIT_ASSET$_114963643);
			Library.addImage(new String("originals/Scene 1/thought_worry.png").split("/").join("."), new FLAKIT_ASSET$_1339359349);
			Library.addImage(new String("originals/forest/bluejay.png").split("/").join("."), new FLAKIT_ASSET$867857076);
			Library.addImage(new String("originals/forest/forest.png").split("/").join("."), new FLAKIT_ASSET$_1857407619);
			Library.addImage(new String("originals/forest/owl.png").split("/").join("."), new FLAKIT_ASSET$1195382361);
			Library.addImage(new String("originals/forest/robin.png").split("/").join("."), new FLAKIT_ASSET$_992673407);
			Library.addImage(new String("originals/forest/THOUGHT_ICE.PNG").split("/").join("."), new FLAKIT_ASSET$1051328945);
			Library.addImage(new String("originals/forest/THOUGHT_SPINKY_CRASH.PNG").split("/").join("."), new FLAKIT_ASSET$1307309286);
			Library.addImage(new String("originals/forest/THOUGHT_SPINKY_TRY_FLY.PNG").split("/").join("."), new FLAKIT_ASSET$279417711);
			Library.addImage(new String("originals/desert/desert.png").split("/").join("."), new FLAKIT_ASSET$_1085353871);
			Library.addImage(new String("originals/desert/HAND_JOURNAL.PNG").split("/").join("."), new FLAKIT_ASSET$_222617567);
			Library.addImage(new String("originals/desert/thought_alert_melt.png").split("/").join("."), new FLAKIT_ASSET$983665735);
			Library.addImage(new String("originals/desert/thought_city.png").split("/").join("."), new FLAKIT_ASSET$2082608830);
			Library.addImage(new String("originals/city/balloon_guy.png").split("/").join("."), new FLAKIT_ASSET$_1570858312);
			Library.addImage(new String("originals/city/city.png").split("/").join("."), new FLAKIT_ASSET$454275398);
			Library.addImage(new String("originals/city/cop.png").split("/").join("."), new FLAKIT_ASSET$546988608);
			Library.addImage(new String("originals/city/no_exit.png").split("/").join("."), new FLAKIT_ASSET$1271420847);
			Library.addImage(new String("originals/city/no_penguins.png").split("/").join("."), new FLAKIT_ASSET$_401733363);
			Library.addImage(new String("originals/city/thought_forest.png").split("/").join("."), new FLAKIT_ASSET$985093860);
			Library.addImage(new String("originals/city/thought_no_exit.png").split("/").join("."), new FLAKIT_ASSET$41517448);
			Library.addImage(new String("originals/city/thought_no_penguins.png").split("/").join("."), new FLAKIT_ASSET$_2096841785);
			Library.addImage(new String("originals/city/thought_penguin_balloon.png").split("/").join("."), new FLAKIT_ASSET$_913814127);
			Library.addImage(new String("originals/city/thought_penguin_balloon_guy.png").split("/").join("."), new FLAKIT_ASSET$532174220);
			Library.addImage(new String("ogmo/ambiance.png").split("/").join("."), new FLAKIT_ASSET$26896941);
			Library.addImage(new String("ogmo/background.png").split("/").join("."), new FLAKIT_ASSET$_1157757234);
			Library.addImage(new String("ogmo/camera.png").split("/").join("."), new FLAKIT_ASSET$_862204225);
			Library.addImage(new String("ogmo/climate.png").split("/").join("."), new FLAKIT_ASSET$910413312);
			Library.addImage(new String("ogmo/Decal.png").split("/").join("."), new FLAKIT_ASSET$338515033);
			Library.addImage(new String("ogmo/director.png").split("/").join("."), new FLAKIT_ASSET$_1319427065);
			Library.addImage(new String("ogmo/emitter.png").split("/").join("."), new FLAKIT_ASSET$_438935123);
			Library.addImage(new String("ogmo/footsteps.png").split("/").join("."), new FLAKIT_ASSET$_1233139147);
			Library.addImage(new String("ogmo/humphrey.png").split("/").join("."), new FLAKIT_ASSET$_1285077015);
			Library.addImage(new String("ogmo/invitem.png").split("/").join("."), new FLAKIT_ASSET$_612164355);
			Library.addImage(new String("ogmo/overworld.png").split("/").join("."), new FLAKIT_ASSET$_1221571681);
			Library.addImage(new String("ogmo/script.png").split("/").join("."), new FLAKIT_ASSET$1622622818);
			Library.addImage(new String("ogmo/smallhumphrey.png").split("/").join("."), new FLAKIT_ASSET$1909618802);
			Library.addImage(new String("ogmo/worldreaction.png").split("/").join("."), new FLAKIT_ASSET$_386300015);
			Library.addImage(new String("ogmo/worldSound.png").split("/").join("."), new FLAKIT_ASSET$1161070485);
			Library.addImage(new String("art/thoughts/coin.png").split("/").join("."), new FLAKIT_ASSET$_288522474);
			Library.addImage(new String("art/snow/snowdrift.png").split("/").join("."), new FLAKIT_ASSET$360635201);
			Library.addImage(new String("art/snow/snowflake.png").split("/").join("."), new FLAKIT_ASSET$1532032240);
			Library.addImage(new String("art/snow/snow_exterior.png").split("/").join("."), new FLAKIT_ASSET$_1731975245);
			Library.addImage(new String("art/snow/thought_big_heart.png").split("/").join("."), new FLAKIT_ASSET$1026734727);
			Library.addImage(new String("art/snow/thought_small_heart.png").split("/").join("."), new FLAKIT_ASSET$520857850);
			Library.addImage(new String("art/pickups/backpack.png").split("/").join("."), new FLAKIT_ASSET$_3860730);
			Library.addImage(new String("art/pickups/desert-coin.png").split("/").join("."), new FLAKIT_ASSET$379953637);
			Library.addImage(new String("art/pickups/journal.png").split("/").join("."), new FLAKIT_ASSET$_2032973506);
			Library.addImage(new String("art/pickups/start-coin.png").split("/").join("."), new FLAKIT_ASSET$1324840388);
			Library.addImage(new String("art/pickups/woods-coin.png").split("/").join("."), new FLAKIT_ASSET$_148402505);
			Library.addImage(new String("art/particles/flame_01.png").split("/").join("."), new FLAKIT_ASSET$_1946428317);
			Library.addImage(new String("art/particles/flame_02.png").split("/").join("."), new FLAKIT_ASSET$_1956717469);
			Library.addImage(new String("art/particles/flame_03.png").split("/").join("."), new FLAKIT_ASSET$_1958880157);
			Library.addImage(new String("art/particles/smoke.png").split("/").join("."), new FLAKIT_ASSET$_489507794);
			Library.addImage(new String("art/particles/snowflake.png").split("/").join("."), new FLAKIT_ASSET$_430274975);
			Library.addImage(new String("art/decals/balloon-platform.png").split("/").join("."), new FLAKIT_ASSET$_530865402);
			Library.addImage(new String("art/decals/balloon.png").split("/").join("."), new FLAKIT_ASSET$_2066801113);
			Library.addImage(new String("art/decals/chair.png").split("/").join("."), new FLAKIT_ASSET$2847401);
			Library.addImage(new String("art/decals/city-hub.png").split("/").join("."), new FLAKIT_ASSET$1850880706);
			Library.addImage(new String("art/decals/city-subway.png").split("/").join("."), new FLAKIT_ASSET$_1015891773);
			Library.addImage(new String("art/decals/desert-hub.png").split("/").join("."), new FLAKIT_ASSET$_1336183665);
			Library.addImage(new String("art/decals/desert-sky.png").split("/").join("."), new FLAKIT_ASSET$_113216755);
			Library.addImage(new String("art/decals/desert-subway.png").split("/").join("."), new FLAKIT_ASSET$1305127734);
			Library.addImage(new String("art/decals/ice_block.png").split("/").join("."), new FLAKIT_ASSET$353445110);
			Library.addImage(new String("art/characters/abe.png").split("/").join("."), new FLAKIT_ASSET$731243959);
			Library.addImage(new String("art/characters/humphrey.png").split("/").join("."), new FLAKIT_ASSET$1976508815);
			Library.addImage(new String("art/backgrounds/city-hub.png").split("/").join("."), new FLAKIT_ASSET$18517733);
			Library.addImage(new String("art/backgrounds/overworld.png").split("/").join("."), new FLAKIT_ASSET$_1423972293);
			Library.addImage(new String("art/backgrounds/snow-basketball.png").split("/").join("."), new FLAKIT_ASSET$_1317921299);
			Library.addImage(new String("art/backgrounds/snow-hub.png").split("/").join("."), new FLAKIT_ASSET$_144923090);
			Library.addImage(new String("art/backgrounds/snow-pond.png").split("/").join("."), new FLAKIT_ASSET$1743609987);
			Library.addImage(new String("art/backgrounds/start.png").split("/").join("."), new FLAKIT_ASSET$_782423215);
			Library.addImage(new String("art/backgrounds/woods-gate.png").split("/").join("."), new FLAKIT_ASSET$_585748117);
			Library.addSound(new String("sounds/crickets.mp3").split("/").join("."), new FLAKIT_ASSET$_451768168);
			Library.addSound(new String("sounds/traffic.mp3").split("/").join("."), new FLAKIT_ASSET$339336096);
			Library.addSound(new String("sounds/windHowl.mp3").split("/").join("."), new FLAKIT_ASSET$_531661301);
			Library.addSound(new String("sounds/footsteps-snow/step-2.mp3").split("/").join("."), new FLAKIT_ASSET$_1434075057);
			Library.addSound(new String("sounds/footsteps-snow/step-3.mp3").split("/").join("."), new FLAKIT_ASSET$_1797078961);
			Library.addSound(new String("sounds/footsteps-snow/step-4.mp3").split("/").join("."), new FLAKIT_ASSET$1292877903);
			Library.addSound(new String("sounds/footsteps-snow/step-5.mp3").split("/").join("."), new FLAKIT_ASSET$_1835745201);
			Library.addSound(new String("sounds/footsteps-snow/step.mp3").split("/").join("."), new FLAKIT_ASSET$_11183610);
			Library.addSound(new String("sounds/footsteps-sand/step.mp3").split("/").join("."), new FLAKIT_ASSET$_1526623850);
			Library.addSound(new String("sounds/footsteps-hard/step-2.mp3").split("/").join("."), new FLAKIT_ASSET$_487780191);
			Library.addSound(new String("sounds/footsteps-hard/step-3.mp3").split("/").join("."), new FLAKIT_ASSET$_353890143);
			Library.addSound(new String("sounds/footsteps-hard/step.mp3").split("/").join("."), new FLAKIT_ASSET$_225120446);
			Library.addXML(new String("Library.xml").split("/").join("."), getXML(FLAKIT_ASSET$_1371418527));
			Library.addXML(new String("worlds/woods-gate/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$_250403341));
			Library.addXML(new String("worlds/start/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$_475205487));
			Library.addXML(new String("worlds/snow-pond/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$1886460785));
			Library.addXML(new String("worlds/snow-hub/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$404816983));
			Library.addXML(new String("worlds/snow-basketball/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$2134780036));
			Library.addXML(new String("worlds/overworld/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$573320175));
			Library.addXML(new String("worlds/desert-hub/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$818774959));
			Library.addXML(new String("worlds/city-hub/map.oel").split("/").join("."), getXML(FLAKIT_ASSET$285960271));
			Library.addXML(new String("scripts/desert-coin-humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$_897355116));
			Library.addXML(new String("scripts/desert-coin.xml").split("/").join("."), getXML(FLAKIT_ASSET$911999451));
			Library.addXML(new String("scripts/rotateWorld.xml").split("/").join("."), getXML(FLAKIT_ASSET$1821305064));
			Library.addXML(new String("scripts/start-coin-humphrey.xml").split("/").join("."), getXML(FLAKIT_ASSET$_623559228));
			Library.addXML(new String("scripts/start-coin.xml").split("/").join("."), getXML(FLAKIT_ASSET$_1949650226));
			Library.addXML(new String("scripts/old/abe-test.xml").split("/").join("."), getXML(FLAKIT_ASSET$1897969838));
			Library.addXML(new String("scripts/old/city-hub.xml").split("/").join("."), getXML(FLAKIT_ASSET$_431966461));
			Library.addXML(new String("scripts/old/humphrey-actions-start.xml").split("/").join("."), getXML(FLAKIT_ASSET$445936569));
			Library.addXML(new String("config/settings.xml").split("/").join("."), getXML(FLAKIT_ASSET$_901571473));
		}
		private function getXML(c:Class):XML{var d:ByteArray = new c;var s:String = d.readUTFBytes(d.length);return new XML(s);}
	}
}
